version: "3.9"

services:
  litellm:
    # DB 연동이 포함된 전용 이미지 사용
    image: ghcr.io/berriai/litellm-database:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
      - LITELLM_USER_AGENT=${LITELLM_USER_AGENT}
      - DATABASE_URL=postgresql://llmproxy:dbpassword9090@db:5432/litellm
      - PROXY_API_KEY=${PROXY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LITELLM_LOG=ERROR
      - LITELLM_MODE=PRODUCTION
    command:
      - "--config=/app/config.yaml"
      - "--detailed_debug"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=llmproxy
      - POSTGRES_PASSWORD=dbpassword9090
      - POSTGRES_DB=litellm
    ports:
      - "5432:5432"
    volumes:
      - litellm_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  litellm_data:
